src/App/ArticleBundle/Entity/Blog.php
<?php

namespace App\ArticleBundle\Entity;

use App\AppBundle\Component\SubdomainHelper;
use App\OfferBundle\Entity\Category;
use App\OfferBundle\Entity\TransactionType;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\ORM\Mapping as ORM;

/**
 * CategoryOfferDescription
 *
 * @ORM\Table(name="blog")
 * @ORM\Entity(repositoryClass="BlogRepository")
 * @ORM\HasLifecycleCallbacks
 */
class Blog
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;
    
    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255,nullable=true)
     */
    private $name;
    /**
     * @var string
     *
     * @ORM\Column(name="city", type="string", length=255,nullable=true)
     */
    private $city;
    /**
     * @var string
     *
     * @ORM\Column(name="subdomain", type="string", length=255)
     */
    private $subdomain;
    /**
     * @var TransactionType transaction type
     * @ORM\ManyToOne(targetEntity="App\OfferBundle\Entity\TransactionType", inversedBy="descriptions")
     */
    protected $transactionType;
    /**
     * @var Category category
     * @ORM\ManyToOne(targetEntity="App\OfferBundle\Entity\Category", inversedBy="descriptions")
     */
    protected $category;
    /**
     * @var Article[] collection of articles
     *
     * @ORM\OneToMany(targetEntity="Article", mappedBy="blog")
     */
    protected $articles;

    /**
     * Blog constructor.
     */
    public function __construct()
    {
        $this->articles = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    
    /**
     * Set city
     *
     * @param string $city
     *
     * @return Blog
     */
    public function setCity($city)
    {
        $this->city = $city;

        return $this;
    }

    /**
     * Get city
     *
     * @return string
     */
    public function getCity()
    {
        return $this->city;
    }


    public function getTransactionType() {
        return $this->transactionType;
    }

    public function setTransactionType(TransactionType $transactionType) {
        $this->transactionType = $transactionType;
        return $this;
    }

    public function getCategory() {
        return $this->category;
    }

    public function setCategory(Category $category) {
        $this->category = $category;
        return $this;
    }

    /**
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param string $name
     * @return Blog
     */
    public function setName(string $name): Blog
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Article[]
     */
    public function getArticles()
    {
        return $this->articles;
    }

    /**
     * @param Article[] $articles
     * @return Blog
     */
    public function setArticles(array $articles)
    {
        $this->articles = $articles;

        return $this;
    }

    public function hasArticles()
    {
        return !$this->articles->isEmpty();
    }

    /**
     * @return string
     */
    public function getSubdomain()
    {
        return $this->subdomain;
    }

    /**
     * @param string $subdomain
     * @return Blog
     */
    public function setSubdomain(string $subdomain): Blog
    {
        $this->subdomain = $subdomain;

        return $this;
    }

    public function isWithoutLocation()
    {
        $params = SubdomainHelper::getParamsFromSubdomain($this->getSubdomain());

        return (count($params) == 2)? true : false;
    }

    public function getTransactionName()
    {
        $params = SubdomainHelper::getParamsFromSubdomain($this->getSubdomain());

        return $params[0];
    }
    public function getTypeName()
    {
        $params = SubdomainHelper::getParamsFromSubdomain($this->getSubdomain());

        return $params[1];
    }

}

src/App/ArticleBundle/Controller/BlogArticleController.php
<?php
/**
 * This file is part of the AppArticeBundle package.
 *
 */
namespace App\ArticleBundle\Controller;

use App\ArticleBundle\Entity\ArticleCategory;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use App\ArticleBundle\Entity\Article;
use App\ArticleBundle\Form\ArticleType;
use App\ArticleBundle\Form\EditArticleType;
use App\ArticleBundle\Entity\Tag;
use App\ArticleBundle\Model\Recommend;
use App\ArticleBundle\Form\RecommendType;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\RedirectResponse;
use \Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use App\AppBundle\Component\SubdomainHelper;
/**
 * Class ArticleController
 *
 * @author wojciech przygoda
 */
class BlogArticleController extends Controller
{
    /**
     * Add article
     *
     * @throws \Doctrine\ORM\ORMException
     */
    public function addAction()
    {
        $request = $this->getRequest();
        $blog = $this->get('blog.manager')->getById($request->get('id'));

        if(!is_object($blog))
        {
            throw new NotFoundHttpException();
        }

        $article = (new Article())
                    ->setBlog($blog)
        ;

        if($request->query->has('idCategory'))
        {
            $category = $this->get('doctrine.orm.entity_manager')
                             ->getReference(ArticleCategory::class, $request->get('idCategory'));
            $article->setCategory($category);
        }

        $form = $this->createForm(new ArticleType($this->getDoctrine()->getManager()), $article);
        $form->handleRequest($request);

        if($form->isValid()){
            $articleManager = $this->get('article.manager');
            $articleManager->add($article,$blog->getId());

            $this->addFlash('success','Zapisano poprawnie.');

            return $this->redirect($this->generateUrl('backoffice_blog_articles_list',[
                'idCategory'=>$article->getCategory()->getId(),
                'id'=>$blog->getId(),
            ]));
        }

        return $this->render('AppArticleBundle:Article:add.html.twig', array(
                'form'=>$form->createView(),
                 'blog'=>$blog
            ));
    }
    /**
     * Edit article
     *
    */
    public function editAction()
    {
        $request = $this->getRequest();
        $articleManager = $this->get('article.manager');

        $article = $articleManager->findById($request->get('id'));
        $this->denyAccessUnlessGranted('owner', $article);

        $form = $this->createForm(new EditArticleType($this->getDoctrine()->getManager()), $article);

        $form->handleRequest($request);

        if($form->isValid()){
            $blog = $article->getBlog();
            $blogId = null;
            if(is_object($blog))
            {
                $blogId = $blog->getId();
            }
            $articleManager->save($article,$blogId);
            $this->addFlash('success','Zapisano poprawnie.');

            return $this->redirect($this->generateUrl('backoffice_blog_articles_list',
                [
                    'idCategory'=>$article->getCategory()->getId(),
                    'id' => $blogId,
                ]
            ));
        }

        return $this->render('AppArticleBundle:Article:edit.html.twig', array(
                'form'=>$form->createView(),
                'article'=>$article,
                'images'=>$articleManager->findAllImages($request->get('id'))
            ));
    }
    /**
     * List of articles
     *
    */
    public function listAction()
    {
        $articleManager = $this->get('article.manager');
        $articleCategoryManager = $this->get('articlecategory.manager');
        $blog = $this->get('blog.manager')->getById($this->get('request')->get('id'));


        return $this->render('AppArticleBundle:BlogArticle:list.html.twig', array(
            'articles'=>$articleManager->getAll(false,$blog->getId()),
            'categories'=>$articleCategoryManager->getAll(),
            'blog'=>$blog
            ));

    }
    /**
     * List of articles from the selected category
     *
     * @param Request $request request
     * @return Response
     */
    public function listByCategoryAction(Request $request)
    {
        $articleManager = $this->get('article.manager');
        $category = $articleManager->findCategoryById($request->get('idCategory'));

        $articles = $articleManager->getAllByCategory();

        return $this->render('AppArticleBundle:Article:listByCategory.html.twig', array(
            'items'=>$articles,
            'category'=>$category,
            'categories'=>$articleManager->getAllCategories(true)));
    }

    /**
     * Delete article
     *
    */
    /**
     * Delete article
     *
     * @param int $id article id
     * @return RedirectResponse
     * @throws \Exception
     */
    public function deleteAction($id)
    {
        $articleManager = $this->get('article.manager');
        $article = $articleManager->findById($id);
        $this->denyAccessUnlessGranted('owner', $article);
        $articleManager->remove($id);
        $this->addFlash('success','Usunięto poprawnie.');

        return $this->redirect($this->getRequest()->headers->get('referer'));
    }

    /**
     * Show article
     *
     * @param $slug
     * @return Response
     */
    public function showAction($slug)
    {
        $article = $this->get('article.manager')->getBySlug($slug,true);
        $subdomain = $this->get('request')->get('subdomain');

        if(!is_object($article)) {
            return $this->redirectToRoute('app_front_page_homepage');
        }
        $blog = $article->getBlog();


        if(empty($subdomain)){
            $subdomain = $this->get('request')->get('transaction') . '-'. $this->get('request')->get('type');
        }

        if($blog->getSuBdomain()!=$subdomain)
        {
            return $this->redirectToRoute('frontend_subdomain_article',[
                'subdomain'=>$blog->getSubdomain(),
                'slug'=>$article->getSlug()]
            ,301);
        }
        $others = $this->get('article.manager')
            ->getOthersByBlogId($article->getId(), $blog->getId());
        $recommend = new Recommend();
        $route = $this->get('article.manager')->generateRoute($article);
        $message = "Witaj\nZnalazłem ciekawy artykuł na stronie wgn.pl.Poniżej link\n ".$route;
        $recommend->setMessage($message);
        $form = $this->createForm(new RecommendType(),$recommend);
        $view = 'show';
        if($this->get('request')->query->has('print')){
            $view = 'printShow';
        }

        return $this->render(sprintf('AppArticleBundle:BlogArticle:%s.html.twig',$view), array(
            'article'=>$article,
            'blog'=>$blog,
            'mainImage'=> $this->get('myimage.manager')->getRandom(),
            'images'=>$article->getImages(),
            'form'=>$form->createView(),
            'h1TextColor'=>$this->get('settings.manager')->get(1)->getH1TextColor(),
            'h1Color'=>$this->get('settings.manager')->get(1)->getH1Color(),
            'items'=>$others,
            ));

    }

    /**
     * Show article in print mode
     *
     * @param int $id article id
     * @return Response
     */
    public function printAction($id)
    {
        $article = $this->get('article.manager')->findById($id,true);
        $category = $article->getCategory();

        $others = $this->get('article.manager')
                       ->getOthersPublishedByCategoryId($id,$category->getId(), 20);

        $recommend = new Recommend();
        $route = $this->get('article.manager')->generateRoute($article);
        $message = "Witaj\nZnalazłem ciekawy artykuł na stronie wgn.pl.Poniżej link\n ".$route;
        $recommend->setMessage($message);
        $form = $this->createForm(new RecommendType(),$recommend);

        return $this->render('AppArticleBundle:Article:show.html.twig', array(
            'article'=>$article,
            'category'=>$category,
            'others'=>$others,
            'images'=>$article->getImages(),
            'form'=>$form->createView(),
            ));

    }

    /**
     * Change article position on list
     *
     * @param int $id article id
     * @param string $direction change ordering direction
     * @return RedirectResponse
     * @throws \Exception
     */
    public function changeOrderingAction($id,$direction)
    {
        $articleManager = $this->get('article.manager');
        $articleManager->changeOrdering($id,$direction);

        $this->addFlash('success','Pozycja została zmieniona.');

        return $this->redirect($this->getRequest()->headers->get('referer'));
    }
    /**
     * Change article publication state
     *
    */
    public function changePublishAction()
    {
        $id = $this->getRequest()->get('id');
        $publish = $this->getRequest()->get('publish');

        $articleManager = $this->get('article.manager');
        $article = $articleManager->findById($id);
        $this->denyAccessUnlessGranted('owner', $article);
        $articleManager->changePublish($id,$publish );

        $this->addFlash('success','Pozycja została zmieniona.');

        return $this->redirect($this->getRequest()->headers->get('referer'));

    }
    /**
     * Send Recommend
     *
     * @return JsonResponse
     * @throws AccessDeniedException
     */
    public function sendRecommendAction(){
        $request =  $this->getRequest();
        $recommend = new Recommend();
        $form = $this->createForm(new RecommendType(),
                                  $recommend);
        $form->handleRequest($request);
        if($request->isXmlHttpRequest() &&
            $form->isSubmitted() && $form->isValid()) {
            $mailer = $this->get('mailer');
            $message = $mailer->createMessage()

src/App/ArticleBundle/Resources/views/BlogArticle/list.html.twig
{% extends "AppBackOfficeBundle:_Partials:layout.html.twig" %}
{% block body %}
    <section class="content-header">
      <h1>
        Lista Artykułów
      </h1>
      <ol class="breadcrumb">
        <li><a href="#" title="Dashboard"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li><a href="#" title="Cms">Blog</a></li>
        <li class="active">Artykuły</li>
      </ol>
    </section>
    <section class="content">
            {% include 'AppBackOfficeBundle:_Partials:flashMessage.html.twig' %}
            <div class="col-md-12">
            <div class="box">
            <div class="box-header with-border">
              <form class="navbar-form navbar-left" action="{{ path('backoffice_blog_articles_list') }}" role="search" method="GET">
                  <input type="hidden" name="id" value="{{ app.request.get('id') }}">
                  <div class="form-group">
                    <h3 class="box-title pull-left">Kategoria </h3>
                  </div>
                  <div class="form-group">
                      <select name="idCategory" class="form-control">
                            {% for cat in categories %}
                                <option value="{{cat.id}}" {% if app.request.get('idCategory') == cat.id %}selected="selected"{% elseif app.request.get('idCategory') is null and cat.id ==1 %} selected="selected" {% endif %}>{{cat.name}}</option>
                            {% endfor %}
                      </select>
                  </div>
              </form>
              <h3 class="box-title pull-right">
                  <a href="{{path('backoffice_blog_article_add',{'id':app.request.get('id'),'idCategory':app.request.get('idCategory')})}}" class="btn btn-success btn-flat" title="Dodaj Artykuł"><i class="fa fa-plus"></i> Dodaj Artykuł</a>
              </h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body scroll">
              <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Nazwa</th>
                            <th width="150">Publikacja od</th>
                            <th width="150">Kategoria</th>
                            <th width="150">Url</th>
                            <th width="150">Kolejność</th>
                            <th width="250">Opcje</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for article in articles %}
                        <tr class="odd gradeX">
                            <td>{{article.name}}</td>
                            <td>{{article.publishDate | date('d.m.Y G:i:s')}}</td>
                            <td>{{article.category.name}}</td>
                            <td>
                                {% if article.isUrl %}
                                    {% set url = article.url %}
                                {% elseif blog.isWithoutLocation %}
                                    {% set url =  domain ~ path('frontend_blog_article_search_url',{slug: article.slug,transaction: blog.transactionName,type:blog.typeName}) %}
                                {% else %}
                                    {% set url = host_scheme ~ ':' ~ path('frontend_subdomain_article',{slug: article.slug,subdomain: blog.subdomain},true) %}
                                {% endif %}
                                {{url}}
                            </td>
                            <td>
                                {%if loop.first and loop.last %}
                                    &nbsp;
                                {%elseif loop.first and articles.getPaginationData()['current'] == 1%}
                                    <a href="#" class="btn btn-default btn-flat disabled" title="Do góry"> <i class="fa fa-arrow-up"></i></a>
                                    <a href="{{path('backoffice_blog_article_change_order',{'id':article.id,'direction':'down'})}}" class="btn btn-primary btn-flat" title="Na dół"> <i class="fa fa-arrow-down"></i></a>
                                {% elseif loop.last and articles.getPaginationData()['current'] == articles.getPaginationData()['endPage']%}
                                    <a href="{{path('backoffice_blog_article_change_order',{'id':article.id,'direction':'up'})}}" class="btn btn-primary btn-flat" title="Do góry"> <i class="fa fa-arrow-up"></i></a>
                                    <a href="#" class="btn btn-default btn-flat disabled"> <i class="fa fa-arrow-down"></i></a>
                                {% else %}
                                    <a href="{{path('backoffice_blog_article_change_order',{'id':article.id,'direction':'up'})}}" class="btn btn-primary btn-flat" title="Do góry"> <i class="fa fa-arrow-up"></i></a>
                                    <a href="{{path('backoffice_blog_article_change_order',{'id':article.id,'direction':'down'})}}" class="btn btn-primary btn-flat" title="Na dół"> <i class="fa fa-arrow-down"></i></a>
                                {% endif %}
                            </td>
                            <td>
                                {% if article.isPublish %}
                                    <a href="{{path('backoffice_blog_article_change_publish',{'id':article.id,'publish':0})}}" class="btn btn-success btn-flat"  data-toggle="tooltip" data-placement="top" title="ukryj"> <i class="fa fa-plus"></i></a>
                                {% else %}
                                    <a href="{{path('backoffice_blog_article_change_publish',{'id':article.id,'publish':1})}}" class="btn btn-danger btn-flat"  data-toggle="tooltip" data-placement="top" title="pokaż"> <i class="fa fa-minus"></i></a>
                                {% endif %}
                                <a href="{{path('backoffice_blog_article_edit',{'id':article.id})}}" class="btn btn-primary btn-flat"  data-toggle="tooltip" data-placement="top" title="edycja"> <i class="fa fa-edit"></i></a>
                                <a href="#" data-href="{{path('backoffice_blog_article_delete',{'id':article.id})}}"  data-toggle="tooltip" data-placement="top" title="Usuń" class="btn btn-danger btn-flat" data-show-modal="delete"> <i class="fa fa-trash-o"></i></a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <!-- /.box-body -->
            <div class="box-footer clearfix">
            {{ knp_pagination_render(articles) }}
            </div>
          </div>
            </div>
                <!-- /.col-lg-12 -->
    </section>
{% include 'AppBackOfficeBundle:_Partials:modalDelete.html.twig' %}
{% endblock body %}
{% block javascripts %}
    <script>

    $('a[data-show-modal="delete"]').on('click',function(){
        $('#confirm-delete').find('.danger').attr('href', $(this).data('href'));
        $('#confirm-delete').modal();
    });
    $('select[name="idCategory"]').on('change',function(){
        $(this).closest('form').submit();
    });
    </script>
{% endblock %}

src/App/ArticleBundle/Resources/views/BlogArticle/printShow.html.twig
{% extends "AppFrontPageBundle:_Partials:printLayout.html.twig" %}
{% block body %}
    <div class="article-box">
        <div class="col-md-8">
            <div class="article">
                <div class="col-md-12">
                    <h3>{{article.category.name}}{% if article.source !='' %}<span class="pull-right source"> &nbsp;| <a href="{{article.source}}" target="blank" title="{{article.source|replace({'http://':''})}}">{{article.source|replace({'http://':''})}}</a></span>{% endif %}<span class="pull-right date">{{article.createDate | date('Y.m.d')}}</span></h3>
                    <h2 class="title">{{article.name}}</h2>
                </div>
                <div class="col-md-12">
                    {% if article.mainPhoto !=''%}
                    <div class="article-main-photo pull-right">
                        <a href="{{ ('/uploads/articles/' ~article.id ~ '/' ~ article.mainPhoto) | imagine_filter('article_big') }}" class="gi" title="{{article.name}}"><img src="{{ ('/uploads/articles/' ~article.id ~ '/' ~ article.mainPhoto) | imagine_filter('article_main_thumbnail') }}" alt="{{article.name}}" class="img-responsive pull-right"></a>
                    </div>
                    {% endif %}
                    {% if article.intro !='' %}
                    <div class="article-intro {% if article.mainPhoto ==''%}no-main-photo{% endif %}">
                        {{article.intro | raw}}
                    </div>
                    {% endif %}
                    <div class="article-text">
                        {{article.content | raw}}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block content_block_top %}{{contentBloks('article_top')}}{%endblock %}
{% block stylesheet %}
    <link href="{{asset('front-layout/lib/lightbox/magnific-popup.css')}}" rel="stylesheet">
{% endblock %}
{% block javascripts %}
    <script src="{{asset('front-layout/lib/lightbox/jquery.magnific-popup.min.js')}}"></script>
    <script src="{{asset('front-layout/lib/validate/validate.min.js')}}"></script>
    <script type="text/javascript">
        window.print();
        var recommendUrl = '{{domain}}{{path('frontend_article_recommend')}}';
      $(document).ready(function() {
        $('.article').magnificPopup({
          delegate: 'a.gi',
          type: 'image',
          tLoading: 'Ładuję #%curr%...',
          mainClass: 'mfp-img-mobile',
          gallery: {
            enabled: true,
            navigateByImgClick: true,
            preload: [0,1] // Will preload 0 - before current, and 1 after the current image
          },
          image: {
            tError: '<a href="%url%">The image #%curr%</a> could not be loaded.',
            titleSrc: function(item) {
              return item.el.attr('title');
            }
          }
        });
      });
      $('#print-article').on('click', function (e) {
            e.preventDefault();
            window.print();
        });
        $('a[data-action="sendRecommend"]').on('click',function(e){
            e.preventDefault();
            $('#modal-recommend').modal();
        });
        $('#modal-recommend form').validate({sendValid:false});
        $('#modal-recommend form').on('form:valid',function(e){
        var self = this;
        var formdata = $(self).serialize();
        $.ajax({
            type: "POST",
            url: recommendUrl,
            data: formdata,
            cache: false,
            beforeSend:function(){
                $('#modal-recommend').find('.btn-success').hide();
                $('#modal-recommend').find('.btn-success').closest('div.col-xs-12').append('<i class="fa fa-spinner fa-spin fa-2x"></i>');
            }
        }).done(function(response){
                if(response.success){
                    $('#recommend-form').html('<h5 class="bg-green"><i class="fa fa-check-circle fa-2x"></i> Formularz został wysłany. Dziękujemy.</h5>');
                }else {
                    alert('Nie udało się wysłać formularza');
                    $('#modal-recommend').find('.btn-success').show();
                }
            });
        });
    </script>
{% endblock %}
{%block metaDescription %}{{article.intro | slice(0,300)}}{% endblock %}
{%block ogDescription %}{{article.intro | slice(0,300)}}{% endblock %}
{%block twitterDescription %}{{article.intro  | slice(0,140)}}{% endblock %}
{%block pageTitle %}{{article.name}} {{getSettings('pageTitle')}}{%endblock%}
{%block ogTitle %}{{article.name}} {{getSettings('pageTitle')}}{% endblock %}
{%block twitterTitle %}{{article.name}} {{getSettings('pageTitle')}}{% endblock %}